Solution
shiryz/pg-workshop pull request #23
Opened 2017-07-21 14:46 UTC by pbywater

Adding a solution branch with a possible answer
- https://github.com/foundersandcoders/master-reference/issues/308

2017-07-27 14:25 UTC, jsms90 commented
@pbywater In the issue, you ask @ConchobarMacNessa and @macintoshhelper to user test this workshop and review your PR, but you haven't assigned them to this PR.

@ConchobarMacNessa @macintoshhelper have you user tested this?

2017-07-27 15:58 UTC, des-des requested changes
wikid

2017-07-27 15:58 UTC, des-des commented on README.md
> +- Install the npm modules `pg` and `env2`: `npm install --save pg env2`.
cant these just be in the package they are pulling down? At that point `npm install` will grab them..?

2017-07-27 15:58 UTC, des-des commented on database/db_connection.js
> +options.ssl = (options.host !== 'localhost');
Move these 3 lines into the options object?

2017-07-27 15:58 UTC, des-des commented on package.json
> +    "env2": "^2.2.0",
Hmm this in in deps and dev deps

2017-07-27 15:58 UTC, des-des commented on package.json
> +    "env2": "^2.2.0"
ie delete this

2017-07-27 15:58 UTC, des-des commented on public/main.css
> +}
indentation in this file needs fixing

2017-07-27 15:58 UTC, des-des commented on src/handlers/getData.js
> +    cb(null, res.rows);
callback getting called twice on error
instead
```js
if (err) cb(err)
else cb(null, res.rows)
```

2017-07-27 15:58 UTC, des-des commented on src/handlers/postData.js
> +      return cb(err);
yes this one is fine. but I think confusing for beginners (since the return is being used to exit the function, but not to return anything)

2017-07-27 15:58 UTC, des-des commented on src/handlers/postData.js
> +      return cb(err);
I would just use the if / else style as is easiest to understand for beginners

```js
if (err) {
  cb(err);
} else {
  cb(null res.rows);
}
```

2017-07-27 15:58 UTC, des-des commented on src/router.js
> +} else if (endpoint === "create-user") {
indentation

2017-07-27 19:51 UTC, shiryz requested changes
One thing that was left from when I created this, database folder should be moved into src.

2017-07-28 15:56 UTC, pbywater commented on src/handlers/getData.js
> +    cb(null, res.rows);
Thanks - I'll fix this

2017-07-29 16:35 UTC, des-des approved these changes

2017-07-29 20:50 UTC, jsms90 commented
Nice work @pbywater :smile: 

Hopefully all the duplication of work between this branch's readme & the `master` branch readme will be avoided in future by #26.

There's still work to be done on this solution. Mostly around handling errors #27 and naming (`getData.js` is a query, not really a whole handler, so this folder prob shouldn't be called `handlers`). But we can sort this out at the same time as the readme & the `master` branch folder namings.

2017-07-29 20:52 UTC, jsms90 approved these changes

2017-07-30 09:10 UTC, merged