Just refactoring without moving CSS
shiryz/pg-workshop pull request #34
Opened 2018-08-08 13:22 UTC by i2xzy

Relates #35 
Should close #27 and #31 
- add public to static file endpoints
- minor refactor for database files in solution
- separate handlers into handlers.js
- use qs with filepaths
- refactor public handling
- handle errors (returning out of if statements)
- change readme to reflect changes

2018-08-08 13:35 UTC, shiryz approved these changes
Looks great! Thanks @i2xzy :sparkles:

2018-08-09 10:23 UTC, eliasmalik requested changes
@i2xzy the CSS was initially added to this challenge as part of an attempt to address the lack of CSS throughout the latter part of the course.

The implementation could be better, and I can see that it may seem jarring to suddenly transition from a DB-related task to a tenuously related CSS task, but I'm not sure I'd want to simply remove it right now without an alternative, otherwise we're simply removing CSS content/practice from the curriculum, which is not really what we want.

I think the refactor is good though and I'm happy to accept this PR if it only contains those changes, subject to my comment below.

2018-08-09 10:23 UTC, eliasmalik commented on solutions/src/handlers.js
> +    if (err) serverError(err, response);
Needs to be a `return` here (and in all the `if (err)` clauses) otherwise the handler will try to respond twice and throw an exception.

2018-08-09 13:29 UTC, m4v15 commented
also if possible please add a description to the PR and link to an issue?

Not 100% clear why this is happening or what exactly you've done without looking at 19 files changed and 4000 lines of code.

I know it's in the commit history, but just best practice etc.

2018-08-15 13:37 UTC, i2xzy commented on solutions/src/handlers.js
> +    if (err) serverError(err, response);
:ok_hand:

2018-11-27 13:51 UTC, mattlub commented
@eliascodes @m4v15 can this be merged?

I haven't reviewed it but it looks like the changes you requested were implemented.

2018-11-27 19:59 UTC, eliascodes commented
I have no objections but don't want to spring changes on mentors the week before delivery. But if @m4v15, @arrested-developer and @yasminhillis are OK with it I'm happy to merge.

2018-11-27 19:59 UTC, eliasmalik approved these changes

2018-11-28 06:41 UTC, m4v15 commented
We are happy for it to be merged, @arrested-developer your mentors call - I think it's @developess & @SleepySheepy172

2018-11-28 20:30 UTC, developess commented
@m4v15 Thanks for checking. I'm very happy for this to be merged - I think it will make the WS much clearer.

2018-11-28 23:56 UTC, merged